app = "webank-next"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80

  [[services.ports]]
    port = 443

  [services.concurrency]
    soft_limit = 25
    hard_limit = 30
